# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=255)),
                ('Description', models.TextField(default='', max_length=1000)),
                ('travel_from', models.DateTimeField(auto_now_add=True)),
                ('travel_to', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Attendee', models.ManyToManyField(related_name='trip_id', to='first_app.User')),
            ],
        ),
    ]
