# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_trip_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateTimeField(),
        ),
    ]
